//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primo.TiP.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primo.TiP.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity to get extracted data from Train In Progress server.
        /// </summary>
        public static string ACTIVITY_DESC {
            get {
                return ResourceManager.GetString("ACTIVITY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Data.
        /// </summary>
        public static string ACTIVITY_NAME {
            get {
                return ResourceManager.GetString("ACTIVITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a source file for extraction.
        /// </summary>
        public static string ERR_NO_FILE {
            get {
                return ResourceManager.GetString("ERR_NO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide TiP server URL for connection.
        /// </summary>
        public static string ERR_NO_SERVER {
            get {
                return ResourceManager.GetString("ERR_NO_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide authorization token for TiP server.
        /// </summary>
        public static string ERR_NO_TOKEN {
            get {
                return ResourceManager.GetString("ERR_NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data returned.
        /// </summary>
        public static string ERR_NOCODE {
            get {
                return ResourceManager.GetString("ERR_NOCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ERR_OK {
            get {
                return ResourceManager.GetString("ERR_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string GROUP_INPUT {
            get {
                return ResourceManager.GetString("GROUP_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string GROUP_OUTPUT {
            get {
                return ResourceManager.GetString("GROUP_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string GROUP_SERVER {
            get {
                return ResourceManager.GetString("GROUP_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string PROP_FILE {
            get {
                return ResourceManager.GetString("PROP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to process.
        /// </summary>
        public static string PROP_FILE_DESC {
            get {
                return ResourceManager.GetString("PROP_FILE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string PROP_RESULT {
            get {
                return ResourceManager.GetString("PROP_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction result in JSON format.
        /// </summary>
        public static string PROP_RESULT_DESC {
            get {
                return ResourceManager.GetString("PROP_RESULT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string PROP_TOKEN {
            get {
                return ResourceManager.GetString("PROP_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization token for TiP server.
        /// </summary>
        public static string PROP_TOKEN_DESC {
            get {
                return ResourceManager.GetString("PROP_TOKEN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string PROP_TYPE {
            get {
                return ResourceManager.GetString("PROP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document was classified by TiP server as the following document type.
        /// </summary>
        public static string PROP_TYPE_DESC {
            get {
                return ResourceManager.GetString("PROP_TYPE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string PROP_URL {
            get {
                return ResourceManager.GetString("PROP_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiP Endpoint URL.
        /// </summary>
        public static string PROP_URL_DESC {
            get {
                return ResourceManager.GetString("PROP_URL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PROPERTIES {
            get {
                return ResourceManager.GetString("PROPERTIES", resourceCulture);
            }
        }
    }
}
